services:
  web:
    build: .
    working_dir: /data 
    command: python main02.py
    links:
      - db
    volumes:
      - .:/data
    ports:
      - "5005:5005"

  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: ruan123
    ports:
      - "3309:3309"